apiVersion: v1
kind: Secret
metadata:
  name: demo-time-secret
  labels:
    app: demo-time
type: Opaque
stringData:
  # Using stringData for easier readability
  # Kubernetes will automatically base64 encode this value
  POSTGRES_PASSWORD: "mysecretpassword"
