# Salin dari 7-app.yml, dengan perbaikan
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-time-app
  labels:
    app: demo-time-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-time-app
  template:
    metadata:
      labels:
        app: demo-time-app
    spec:
      containers:
        - name: app
          image: sammidev/demo-time:1.0.0
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: demo-time-config

          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-time-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-belajar
  labels:
    app: demo-time-app
spec:
  type: NodePort
  selector:
    app: demo-time-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
